### ISSUE TITLE
Dropdown: 'startsWith' filter works by word rather than start of a String

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#1606]
**Describe the bug**
The 'startsWith' filter currently works on words of a String, rather than start of a String (see below for example). Currently, there is no way to filter on start of a String.

Example list:
![list](https://user-images.githubusercontent.com/45232365/52408963-05c4f680-2acc-11e9-94f2-d090bd6d2cbe.png)

If I enter 'C' I expect 'Correction' to be selected. This works
![filtered-list-1](https://user-images.githubusercontent.com/45232365/52408976-0cec0480-2acc-11e9-87b2-85e77c0525ed.png)

However, if I enter 'A' I expect ''Allocated' to be selected but instead 'Not Allocated' is selected. It seems that the 'startsWith' works on word splits.
![filtered-list-2](https://user-images.githubusercontent.com/45232365/52409004-1f663e00-2acc-11e9-95a3-9489dc6aa071.png)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-filter-types.html
2. Enter 'S' into 'StartsWith Filter' dropdown.
3. 'American Samoa' selected by default

**Expected behavior**
Expected 'South Carolina' to be selected by default

**Version**
Found in 4.14.0, exists in 4.15.0

**Platform**
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:  Version 72.0.3626.81 (Official Build) (64-bit)

**Additional context**
Discussion had with @tmcconechy and thought process was to change existing 'startsWith' behavior to filter based on start of String, and to add a new filter option such as 'startsWithWord' to filter based on the current behavior of 'startsWith'.

**Comment by rvaja-infor** [comment]
What is the update on this issue? Will anybody be picking this up soon, as the SunSystems application has customers that are awaiting resolution of this.

**Comment by tmcconechy** [comment]
We didnt have this one on our radar for immediate but i will bring it up in tomorrow's sprint planning

**Comment by clepore** [comment]
So after some more investigation, the datagrid `startsWith()` does filter only if the entire search string starts with the search term. It seems that the functionality differs between dropdown and datagrid, and dropdown should be fixed to match.

1. You can see all available options here:
    ![image](https://user-images.githubusercontent.com/742319/58512746-d36b0200-816b-11e9-98e1-be3a2ed19c51.png)

2. If you search for "Love" which is the second word, it doesn't "see" it, which is correct.
    ![image](https://user-images.githubusercontent.com/742319/58512770-e382e180-816b-11e9-86b9-729f0a4dcabc.png)

**Comment by tmcconechy** [comment]
Yeah I think at the time the design showed starts with each word so we did them at separate times and they work different. This fix should address the inconsistency in setting name and functionality

**Comment by clepore** [comment]
See ["startsWith" setting in the source code](https://github.com/infor-design/enterprise/blob/master/src/components/listfilter/listfilter.js#L147-L164).

**Comment by janahintal** [comment]
Failed QA. Issue still exist. 
![image](https://user-images.githubusercontent.com/45757016/59739188-6e9c5680-9296-11e9-9758-c2b581d99dad.png)

**Comment by EdwardCoyle** [comment]
@janahintal we didn't change the default functionality, only deprecated the old filter name.  That test should probably be updated with the new filter name, but the functionality there is correct.

**Comment by tmcconechy** [comment]
Actually @EdwardCoyle did we make an example for him on this issue of it filtering just at the start of the whole string not on the word seperation? Just to prove that works? Might be what @janahintal is refering to as the solution isnt actually shown.

**Comment by rvaja-infor** [comment]
On the note of deprecation. For how many releases is something left deprecated before it is fully removed?

**Comment by tmcconechy** [comment]
@rvaja-infor about 3 versions (months)

**Comment by EdwardCoyle** [comment]
@tmcconechy there isn't a page that demonstrates it, but there is a [functional test](https://github.com/infor-design/enterprise/blob/master/test/components/listfilter/listfilter-api-string.func-spec.js#L109-L118)

**Comment by EdwardCoyle** [comment]
Just re-opening for the moment.  I'm going to push a better example that demonstrates all the Dropdown filter methods.

**Comment by janahintal** [comment]
QA Passed. Tested in https://master-enterprise.demo.design.infor.com/components/dropdown/test-filter-types.html across all browser, OS and devices.
