### ISSUE TITLE
Datagrid: Time filter does not filter correctly client side.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2281]
**Describe the bug**

**To Reproduce**
1. Go to 'components/datagrid/test-filter-datetime-client-side.html'
2. Filter by the time field, eg greater than 1:00 AM, 1:00 PM

**Expected behavior**
The filtering is based on just the time 

**Version**
4.19.x

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/58673624-5fa74000-838b-11e9-9d17-3697ff18e7c6.png)
![image](https://user-images.githubusercontent.com/39749678/58673691-aeed7080-838b-11e9-9d74-39a138c0496b.png)

**Platform**
All devices and browsers

**Comment by marknolaninfor** [comment]
This item was corrected in 4.19 10 days ago, so should have been closed then

**Comment by tmcconechy** [comment]
Added this to 4.20 to get looked at by QA.

**Comment by janahintal** [comment]
Failed QA. There is an unnecessary  alert showing upon loading the page https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-datetime-client-side.html
![image](https://user-images.githubusercontent.com/45757016/59755737-090e9100-92bb-11e9-8056-3117be4315fe.png)

**Comment by janahintal** [comment]
Hi @tmcconechy, decimal is still not working in Windows10 Chrome browser for https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html

**Comment by tmcconechy** [comment]
@janahintal made a new PR for this. Decided that the column should actually be integer so removed all decimals. As the other column tests decimal. This one should really just test integer.

**Comment by janahintal** [comment]
QA Passed. Will Move to  Done. 
Tested in: 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html
