### ISSUE TITLE
Datagrid: Filter is returning wrong result

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2553]
**Describe the bug**
Datagrid: Filter is returning wrong result.

Affected pages:
- http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
- http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
- All datagrid pages with filter

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
2. Select "Contains" filter in ID column, then type 5test
3. See issue: Datagrid will return rows with ID 5
4. Select "Equals" filter in ID column, then type 5test
5. See issue: Datagrid will return rows with ID 5
6. This is also happening in other columns except for Product Name

**Expected behavior**
Filter should return correct result

**Version**
- ids-enterprise: v4.11.0 to v4.20.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62105505-2b8dc400-b2d5-11e9-87d3-5192cf24a3d5.png)

**Platform**
 -All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This issue as noted goes way back but this is important functionality. We should look to fix this when possible. Especially if other teams notice. I do not think this is a demo app issue

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue. Must have been fixed at some point. Moving in to verify QA

**Comment by brianjuan** [comment]
QA Passed in http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html. 

But in http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html, the issue still persist in Product ID column. Try to filter Contains "24test", the datagrid will still return rows that contain "24".
![image](https://user-images.githubusercontent.com/39508864/73736152-47d65600-477b-11ea-8571-0d763e97635a.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light

**Comment by brianjuan** [comment]
QA Passed in both http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html and http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html. Will retest once beta is deployed.
