### ISSUE TITLE
Datagrid: Add Unselectable rows feature

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#4499]
**Is your feature request related to a problem or use case? Please describe.**
We have a use-case similar to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-summary-row and https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping-totals. 

We've implemented subtotal and total rows in a bit of a different way. These rows are part of the dataset and we not drawing their checkboxes via the column formatter. The issue we encounter is when clicking on the header checkbox, those rows that only shows aggregate/summary data are also being selected. If we check only the rows with checkboxes, the header checkbox only indicates partial selection.

**Describe the solution you'd like**
I would like to propose for a reserved property in the dataset to be used for decorative rows such us our's (e.g. `unselectable=true`) which would be prevent them from being selected during for `selectAllRows()` and skip them from the count tally in `syncHeaderCheckbox()`

**Describe alternatives you've considered**
I have also considered just filtering the selected rows array we receive on our end during select all however this does not solve the visual mismatch from the header checkbox when you just select the rows individually. (like the screenshot below)

**Additional context**
Here is a sample of how our subtotals and total rows look like:
![image](https://user-images.githubusercontent.com/11013464/96096662-a8b94f00-0f02-11eb-8b9a-a36f1fa0602b.png)

**Comment by tmcconechy** [comment]
We are trying to get away from putting settings in the dataset as folks have been asking that to be untouched so wouldnt want to set a new president. But open to ideas, but also not sure i understand the issue because when i try this on http://localhost:4000/components/datagrid/example-summary-row by adding multiselect functionality, i dont see any problem with it

![Screen Shot 2020-10-15 at 9 50 54 AM](https://user-images.githubusercontent.com/814283/96138762-19914480-0ecc-11eb-9720-971336d8700c.png)

Also the screen shot you used doesnt show any issue to me? Or is it that you dont want line 5 to be selectable?

**Comment by nbcp** [comment]
Yes that is correct for summary-row, however as I've mentioned above, our use case includes adding those special rows within the dataset and we customize display & columns (e.g. show/hide checkboxes) via column formatters. The screenshot I posted show the partial select indicator on the header checkbox instead of the check icon (indicating all records selected), this is because those special rows that are part of the dataset are being counted as part of the select all even without a visible checkbox. So what I am proposing is to have a way to set rows within the dataset to be selectable or not. The concept is somehow similar to disabled options from a menu/dropdown where you can see them on the list, but you're not allowed to select them.

**Comment by tmcconechy** [comment]
ok, sorry im still a little unclear what you want to be able to configure exactly (we can talk about a solution after).

So given this, you want a way so that row "5" both has no checkbox and cant be selected on the rows? I.E. make some rows unselectable with a function or config? And this means NO UI change, just it doesnt select and has no checkbox?

![image](https://user-images.githubusercontent.com/814283/96263794-6b4fd280-0f91-11eb-9579-7a0095825c05.png)

Would this be a correct summary? One reason im asking is we have not selectable rows but we implemented these as disabled. https://master-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html

**Comment by nbcp** [comment]
Thanks @tmcconechy! This is exactly what I needed I can just overwrite the disabled row style. The isRowDisabled config function works, however there is a bug, the header checkbox still doesn't display as check icon (all rows checked). It still shows as partially selected, which might look confusing for some users when they click on it.

**Comment by tmcconechy** [comment]
Ok, its probably just doing a row count excluding the non selectable rows. You could maybe turn it off with showSelectAllCheckbox option?

Do you think we should add something here? Or just fix that issue and your good?

**Comment by nbcp** [comment]
I don't think we'd want to hide the header checkbox since it's a very nice and convenient feature. Maybe for now we just need to fix the sync in row count for it to display properly? Also I'd like to ask if we already have a config/way to set row style? (some way to add a css class to be able to customize some rows)

**Comment by tmcconechy** [comment]
It was an idea for a workaround. And also checking if that is now the only thing needed here? We can fix it I think. What if we do this:

- make select all checkbox work with disabled
- allow a custom class for disabled (or for disabled rows to not look disabled)
- There actually isnt a row css function to add a cssClass at the moment. Its on the columns, so you could in theory add a function to every column to take care of it on each cell. https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L4040 but we could add a row css too someday

**Comment by nbcp** [comment]
Sure! Sounds good. Thanks

**Comment by tmcconechy** [comment]
Think we can close this - as it has a workaround. For version 5.0 will keep improving this
