### ISSUE TITLE
Datepicker: Hr-hr (Croatian) doesn't work with datepicker

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4964]
**Describe the bug**
When a date and time is selected in the datepicker in Croatian the error icon appear. We are also seing a console error in Homepages.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=hr-HR
2. Click on 'the first datepicker
3.Click on a date
3. See error

**Expected behavior**
The date and time should be added in the input field without any issue.

**Version**

- ids-enterprise: 4.37.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/111647846-1c89bb80-8803-11eb-9799-a2d300b0f5a7.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 89.0.4389.90 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
This issue is now resolved. moving ticket to Done. Thanks
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html
![image](https://user-images.githubusercontent.com/56722184/116038329-e9f19f00-a69b-11eb-845d-e9c596a65ce1.png)

**Comment by SofiK** [comment]
Although, there it looks like it is not using Croatian locale? Aren't they using d.M.yyyy in Croatia?

**Comment by SofiK** [comment]
Actually when I try to open https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=hr-HR it doesn't work. When I click a datepicker it reloads and changes to https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?dp1=&dp2=&dp3=&dp4=
Andd then reloads every time I try to use the datepicker!

Also it still fails in :
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=hr-HR

**Comment by tmcconechy** [comment]
We changed master to main so the new link is https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=hr-HR

these are what we had in the CLDR for this https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/hr-HR.js#L16 but happy to update it based on feedback from a natice speaker

**Comment by SofiK** [comment]
Ah, now it works much better! 
Thank Tim!

**Comment by SofiK** [comment]
I only have Wikipedia as my source and noticed that the image in the QA comment was not using dots and was different from the first image of the issue. But it looks good when I use the correct link!

**Comment by jbrcna** [comment]
oh yeah, thanks for catching that @SofiK . comment is updated with correct link and screenshot for reference ☺
