### ISSUE TITLE
Splitter Component: Collapse button not working properly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#5121]
**Describe the bug**
Splitter collapse button is not working properly and looks off in Test page
**To Reproduce**

1. Go to Test page https://main-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html
or 
https://main-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html
2. Splitter collapse button is not working properly and looks off in 
3. Please see screen shot attached. 

**Expected behavior**
Splitter collapse button should be working properly 

**Version**

- ids-enterprise: [e.g. v4.5.1 ]

**Screenshots**
 
![Splitter2](https://user-images.githubusercontent.com/39101346/115731839-75de9080-a355-11eb-8f45-e29748596026.png)
![Spitter1](https://user-images.githubusercontent.com/39101346/115731841-75de9080-a355-11eb-90fe-c6a285b2a26c.png)

**Platform**
 - All Browsers

**Additional context**
None

**Comment by yohannahbautista** [comment]
@CindyMercadoReyes may I ask for more details on the splitter button not working properly? Besides the position of the button, I'm not sure what other bugs are present

**Comment by tmcconechy** [comment]
The issue as a i see it @yohannahbautista is just that the icon is not in the right spot. it should be in the middle of the bar....

![Screen Shot 2021-06-11 at 9 26 46 AM](https://user-images.githubusercontent.com/814283/121693542-3f8cda00-ca97-11eb-9826-58e5f011076d.png)

But it seems to work. I think it certain positions you might not be able to click it but if you fix that, should solve this issue

**Comment by nganotice** [comment]
Hi @yohannahbautista - there's still an issue here wherein it isn't clickable. Kindly check the gif below:

![Splitter issue](https://user-images.githubusercontent.com/84306838/122742731-d6883c00-d2b8-11eb-96e7-11491691f482.GIF)

Thanks!

**Comment by tmcconechy** [comment]
@nganotice I think in that case its because you resized it all the way to the right first so its toggling it back to that position. That is sort of the functionality of it so in that case would have to drag it back in position to reset the position. I think its not worth the time.

**Comment by nganotice** [comment]
Will move this to Done then. Thanks @tmcconechy
