### ISSUE TITLE
Listview: alert icon is missing in RTL

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#5827]
**Describe the bug**
When using `class="alert-text"` in Listview in RTL mode the red icon disappears

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-status.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-status.html?locale=he-IL)
2. See that the icon is missing
3. Compare with [https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-status.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-status.html)
4. it was OK in previous version [https://design.infor.com/code/ids-enterprise/4.34.3/demo/components/listview/example-status.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/4.34.3/demo/components/listview/example-status.html?locale=he-IL)

**Expected behavior**
Icons should be visible in

**Version**

- ids-enterprise: v4.56.0
- it was OK in previous versions for example in v4.34

**Screenshots**
LTR:
![image](https://user-images.githubusercontent.com/34129313/140892184-d9ef53e8-9db5-4ae1-a9b2-051fc3b9eb90.png)
RTL:
![image](https://user-images.githubusercontent.com/34129313/140892127-728f9756-b312-409a-8924-a8d7b24490e8.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 95

**Additional context**
Thanks

**Comment by jbrcna** [comment]
v4.59.0-dev
this is now working as expected. However, I noticed that in Safari the parenthesis is different. see image below.
verified in https://main-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL
![image](https://user-images.githubusercontent.com/56722184/145330260-e6bb5fd7-b010-49da-a402-554fb28865f3.png)

Classic
![image](https://user-images.githubusercontent.com/56722184/145330364-69eb3c9b-3822-414f-b1e0-6aae04781b07.png)

Browserstack: Mac OS Monterey Safari 15
![image](https://user-images.githubusercontent.com/56722184/145331391-47ebd8dc-f82e-433d-baf7-8fc669c965ed.png)

**Comment by jonathanamiran** [comment]
Thanks.
I confirm that also in Chrome Mobile and Android WebView it works as expected.
![image](https://user-images.githubusercontent.com/34129313/145362902-28b2d2db-f496-43c6-b337-c7f68c88c93d.png)


In Firefox (Windows) there's still an issue. However, we use Chrome Windows and Android WebView so Firefox is quite irrelevant for us.

![image](https://user-images.githubusercontent.com/34129313/145362176-25b0ff77-bf6d-4d14-bba8-a101add8449f.png)

**Comment by tmcconechy** [comment]
@jonathanamiran I think this is just a byproduct of it being english text and being RTL and how the browser treats it. So i dont think we can fix that but it should be ok with native text.

I do see the ff issue on https://main-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL still so we should fix that. Reopening for @ericangeles to take a second look

**Comment by jonathanamiran** [comment]
Just to make sure, with Hebrew characters in Chrome it looks great:
![image](https://user-images.githubusercontent.com/34129313/145425462-4c693568-70f8-4062-9c26-b1c0992a5092.png)

But in FF there's still a problem:
![image](https://user-images.githubusercontent.com/34129313/145425649-ad838b90-e264-4b19-8391-6afb386f595a.png)

**Comment by jbrcna** [comment]
QA Passed
 v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL
`Safari`
![image](https://user-images.githubusercontent.com/56722184/146746750-dc3eb760-6e24-4e72-ae2a-792f79cf8d6c.png)

`Chrome`
![image](https://user-images.githubusercontent.com/56722184/146746769-c4c7bd37-4b0e-4388-9806-e86472605f59.png)

`Firefox`
![image](https://user-images.githubusercontent.com/56722184/146746796-75625a1b-da0f-4c67-96b5-d40d97f98724.png)

`Edge`
![image](https://user-images.githubusercontent.com/56722184/146746814-9e4ca388-ecdb-45c8-8737-118113466fbb.png)

`Mobile`
![image](https://user-images.githubusercontent.com/56722184/146748099-7367aa09-786e-4835-8783-af0528dd8515.png)
