### ISSUE TITLE
Button: Disabled primary button has incorrect color

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7185]
**Describe the bug**
I'm not sure if this is a bug or feature, but the text inside a disabled "primary" button is gray in light theme, with the default color. Also the icon is gray inside disabled primary buttons for non-default personalization colors.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/4.80.0/demo/components/button/example-index?theme=uplift&variant=light
2. Observe colors of the disabled "primary" buttons

**Expected behavior**
I would expect the text color to be white

**Version**

- ids-enterprise: 4.80.0

**Screenshots**
Default personalization color:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/4991954/217577417-a7e2d3a4-3074-424b-b4e4-f54c67d4514c.png">

Possibly related, [icon color also seems incorrect in non-default personalization colors:](https://design.infor.com/code/ids-enterprise/4.80.0/demo/components/button/example-index?colors=8D0B0E&theme=uplift&variant=light)
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/4991954/217577993-df86dfd5-e31c-4a58-aa0e-d39b78e9d83e.png">

**Comment by tmcconechy** [comment]
@anhallbe this issue was fixed on main for the next version but it missed the 4.80 code cut off 

https://main-enterprise.demo.design.infor.com/components/button/example-index?theme=uplift&variant=light

https://main-enterprise.demo.design.infor.com/components/button/example-index?colors=8D0B0E&theme=uplift&variant=light

**Comment by tmcconechy** [comment]
@ericangeles do you exactly know which issue this was fixed on? too many issues....

**Comment by ericangeles** [comment]
I fixed that on the disabled button issue. I noticed that too.

**Comment by ericangeles** [comment]
It's here https://github.com/infor-design/enterprise/pull/7169/files#diff-4c5d2cb9327946a7533f5f56f8f639093c56062fd8aa12ea2a0d3b71214e4d7aR205

**Comment by tmcconechy** [comment]
ok useful in case we need to patch ~might just want to release main as a patch if needed. Marking fixed for now

**Comment by anhallbe** [comment]
Nice! Thanks ❤️

**Comment by glenlieorillo** [comment]
The bug still exists in Classic Version. The buttons are disabled. Thus, the font color should be gray.

![image](https://user-images.githubusercontent.com/102151352/217779223-6f8fa7de-a853-4bd8-b2db-5feebfcc7ed2.png)




https://user-images.githubusercontent.com/102151352/217778181-a9d227fd-056f-4602-be10-c55421539cb5.mov

**Comment by glenlieorillo** [comment]
Bug still exists upon changing color in Classic Version.

![image](https://user-images.githubusercontent.com/102151352/220231699-3f8cebe3-5ffb-4dbb-bfba-e4fea8d876ba.png)

![image](https://user-images.githubusercontent.com/102151352/220231795-5de97bb8-09d8-4de3-8fd9-a3ae8dd40af8.png)

https://user-images.githubusercontent.com/102151352/220231518-bf023984-6636-44ba-ae9e-b71cb1e552a8.mov

**Comment by ericangeles** [comment]
@glenlieorillo it hasn’t been fixed yet. The PR is still open.

**Comment by glenlieorillo** [comment]
The bug still exists. See the screenshots below:

**Classic** Version, **Dark** Mode, change the color
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/222628083-537d0472-7272-474e-ab1d-b9c2e3ead814.png">

**Classic** Version, **High Contrast** Mode, change the color
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/222629954-420cae4a-f343-4c22-b37e-426540ba8c92.png">

**Comment by ericangeles** [comment]
@glenlieorillo as per checking again the design in Figma, the color of the font is really white. Moving this to Passed QA.
